###*
Generated by langular: Copyright Edoardo Tenani - MIT license (c) - 2014
-----------------------------------------------------------------------------
###
module.exports = (grunt) ->
  path = require("path")

  # Show grunt execution times - https://github.com/sindresorhus/time-grunt
  require("time-grunt") grunt

  # Load task Just In Time - https://github.com/shootaroo/jit-grunt
  require("jit-grunt") grunt,
    useminPrepare: "grunt-usemin"

  # This package module didn't auto load from jit
  grunt.loadNpmTasks 'grunt-bower-requirejs'

  # Load grunt tasks options from separate folder - https://github.com/firstandthird/load-grunt-config
  require("load-grunt-config") grunt,
    configPath: path.join(process.cwd(), ".grunt") #path to task.js files, defaults to grunt dir
    config:
      fonts:
        extensions: [
          "eot"
          "ttf"
          "woff"
          "svg"
        ].join(",")

      images:
        extensions: [
          "png"
          "jpg"
          "jpeg"
          "gif"
          "webp"
          "svg"
        ].join(",")


    # disable auto loading tasks, loaded via jit-grunt
    loadGruntTasks: false


  # Run with: grunt switchwatch:target1:target2 to only watch those targets
  # HACK THE BOX! https://github.com/gruntjs/grunt-contrib-watch/issues/240#issuecomment-34563443
  grunt.registerTask "customWatch", ->
    targets = Array::slice.call(arguments, 0)
    Object.keys(grunt.config("watch")).filter((target) ->
      (grunt.util._.indexOf(targets, target) is -1)
    ).forEach (target) ->
      grunt.log.writeln "Ignoring " + target + "..."
      grunt.config [
        "watch"
        target
      ],
        files: []

      return

    grunt.task.run "watch"
    return

  grunt
